[package]
name = "borg-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
borg-core.workspace = true
async-trait.workspace = true
futures-core = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
